title: dmp
date: 2014
columns: 1
columnsmode: packed
content: | 
 DMP is a discreet visual aggregator. The small container house electronics that enable anyone within range to easily send videos or photos to be automatically displayed, without any content filtering.
 
 __Ethos__:
  DMP will cycle and loop through the submitted material, cueing up videos or photos on itself. This automated intervention aims to address the availability and ubiquity of transmission channels in public space. This voluntary surveillance dynamic is meant to question people’s sense of self-censorship and the conflict space that exist between initiated & experienced surveillance in situation that offer instant feedback.