title: Logos
date: 2014
1.aflc.top.jpg:
    description: Logo for À Fond La Caisse
2.augusta.top.jpg:
    description: Instruction manual for Air Medic
3.pnp.top.jpg:
    description: Pride and Pugilism logo
4.af.top.jpg:
    description: Logo for AF Design
5.antiflash.top.jpg:
    description: Logo for Antiflash Games

columnmode: column-pack
ignore: true
columns: 1
content: |
 On-going collection of logos that I've designed.