title: The Curated Room
date: 2014
columns: 1
slideinterval: 5

Untitled-2.jpg:
    description: The Four Doors
Untitled-3a.jpg:
    description: North
Untitled-3b.jpg:
    description: West
Untitled-3c.jpg:
    description: East (details)
Untitled-3d.jpg:
    description: East
Untitled-3e.jpg:
    description: East (details)
Untitled-3f.jpg:
    description: East (details)
Untitled-3g.jpg:
    description: (South)	
Untitled-5a.jpg:
    description: The Sill
Untitled-5b.jpg:
    description: Left to right: Emergency Neatness Cancelors, The Loaded Die (5), Blue 4/4, Tim Horton Anti-Arrythmia Tx, Ambition Generator, Ambition Substitutes
Untitled-5c.jpg:
    description: Left to right: Emergency Neatness Cancelors, The Loaded Die (5), Blue 4/4, Tim Horton Anti-Arrythmia Tx, Ambition Generator, Ambition Substitutes	

content: | 
 Pictures of the Curated Room Number One, 7542 Champagneur.