title: Pride and Pugilism
date: 2014
columns: 1
ignore: true
columnsmode: packed
content: | 
 Pride and Pugilism is a work in progress. It is a tactical, turn-based game of fisticuffs set in England in the early 19th century. I am/was mainly involved in game design, sounds, environments and branding.
 
 __Ethos__:
 Two players take turns moving around a grid-based arena, performing attacks, defending, or using special moves against each other. The goal is to knock your opponent out by reducing their health to zero. Pride and Pugilism aims to marry the strategic nature of tactical RPGs with the fast-paced twitch gameplay of contemporary fighting games.