title: Failles
date: 2013
columns: 1
slideinterval: 5
content: |
 Serie of twelve black in white pictures, produced in book form. 8" x 8", 13 pages.
 
 "Of course, the familiar experience of what we see most often seems to give rise to an asset: in seeing something, we generally feel as if we have gained something. But the modality of the visible becomes inevitable - that is to say, doomed to be a matter of being - when to see is to feel that something inevitably escapes us, in other words: when seeing blinds us."
 
  George Didi-Huberman, in Ce Que Nous Voyons, Ce Qui Nous Regarde (Éditions de Minuit, 1992).
  
  
 