title: ■■■■■■■.ws / retention
date: 2014
columns: 1
columnsmode: packed
content: | 
 Retention as in what we leave behind, intentionally or not; what we hold on to as keepsakes; what we decide to show and what we decide to bury.
 
 __Ethos__:
  ■■■■■■■.ws is an online application made to display, access and modify a year's worth of text messages. It aims to overload the viewer-voyeur both with visual and factual informations and offers a mediated access to the numerous exchanges.